# Generated by Django 3.2 on 2022-07-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('availability', models.CharField(choices=[('BUSY', 'Busy'), ('FREE', 'Free'), ('UNAVAILABLE', 'Unavailable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=11, verbose_name='Availability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('availability', models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy')], max_length=11)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField(null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0)),
                ('is_recuring', models.BooleanField(default=False, editable=False)),
                ('recurence', recurrence.fields.RecurrenceField()),
                ('availability', models.CharField(choices=[('BUSY', 'Busy'), ('UNAVAILABLE', 'Unavailable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=11, verbose_name='Availability')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
